alias edit="emacs -nw" fine tune functions for blender build

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -22,20 +22,84 @@ detect_distro() {
   fi
 }
 
+# blender build help info
+#
+function print_build_blender_help () {
+
+    cat << EOF
+
+FUNCTION ARGUMENTS:
+
+    -h, --help
+        Show this message and return.
+
+    -s <path>, --source=<path>
+        Use a source code path (defaults to '\$SRC').
+
+    -i <path>, --install=<path>
+        Path where to install blender (defaults to '\$INST').
+
+    -b <path>, --build=<path>
+        Path to build cmake project. (defaults to '\$BUILDPATH').
+
+EOF
+
+}
+
 # blender build helper
 #
 # run this function in the blender source directory
-build_blender () {
+function build_blender () {
 
-    local PREFIX="$HOME/.local"
+    # copy from blender svn source
+    local SRC="./"
+    local INST=".local"
+    local BUILDPATH="./build"	# build dir for cmake
 
-    mkdir -p build || (echo "Fail to create folder for building! Abort
-    ..."; exit 1)
+    local ARGS=`getopt -o "hs:i:b:" -l "help,source:,install:,build:" -n "getopt.sh" -- "$@"`
+    if [ $? != 0 ]; then echo "Terminating..." >&2; return 1; fi
 
-    pushd ./build
-    
+    eval set -- "$ARGS"
+    while true; do
+	case $1 in
+	    -h|--help)
+		print_build_blender_help
+		shift
+		;;
+	    -s|--source)
+		SRC="$2"
+		shift 2
+		;;
+	    -i|--install)
+		INST="$2"
+		shift 2
+		;;
+	    -b|--build)
+		BUILDPATH="$2"
+		shift 2
+		;;
+	    --)
+		shift
+		break
+		;;
+	    *)
+ 		echo "Wrong parameter!"
+		return 1
+		;;
+	esac
+    done
 
-    cmake ../ -DBUILD_SHARED_LIBS:BOOL=OFF \
+    # get the absolute path
+    SRC=`readlink -f ${SRC}`
+    BUILDPATH=`readlink -f ${BUILDPATH}`
+    INST=`readlink -f ${INST}`
+
+    # mkdir -p $BUILDPATH || (echo "Fail to create folder for building! Abort \
+    # ..."; return 1)
+
+    pushd $BUILDPATH
+
+    cmake $SRC -DBUILD_SHARED_LIBS:BOOL=OFF \
 	-DWITH_FFTW3:BOOL=ON \
 	-DWITH_JACK:BOOL=ON \
 	-DWITH_CODEC_SNDFILE:BOOL=ON \
@@ -58,7 +122,7 @@ build_blender () {
 	-DPYTHON_LIBPATH=/usr/lib64 \
 	-DPYTHON_LIBRARY=python3.3m \
 	-DPYTHON_INCLUDE_DIRS=/usr/include/python3.3m \
-	-DCMAKE_INSTALL_PREFIX:PATH=${PREFIX}
+	-DCMAKE_INSTALL_PREFIX:PATH=${INST}
 
     make
 
